/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MCsCafe;


/**
 *
 * @author harig
 */
public class MenuPage extends javax.swing.JFrame {

    /**
     * Creates new form MenuPage
     */
    public MenuPage() {
        initComponents();
        java.io.File file = new java.io.File(System.getProperty("user.dir") + "\\lib\\log.txt");
        if (!file.exists()) {
            try {
                file.createNewFile();
            } catch (java.io.IOException ex) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FoodRegistration = new javax.swing.JButton();
        BuyerRegistration = new javax.swing.JButton();
        UserRegistration = new javax.swing.JButton();
        Bill = new javax.swing.JButton();
        Postpaid = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Purchase = new javax.swing.JButton();
        Queue = new javax.swing.JButton();
        Pending = new javax.swing.JButton();
        BillStatistics = new javax.swing.JButton();
        MenuCard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu Page | MC's Café");

        FoodRegistration.setMnemonic('F');
        FoodRegistration.setText("Food Registration");
        FoodRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodRegistrationActionPerformed(evt);
            }
        });

        BuyerRegistration.setMnemonic('R');
        BuyerRegistration.setText("Seller Registration");
        BuyerRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyerRegistrationActionPerformed(evt);
            }
        });

        UserRegistration.setMnemonic('U');
        UserRegistration.setText("User Registration");
        UserRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserRegistrationActionPerformed(evt);
            }
        });

        Bill.setMnemonic('B');
        Bill.setText("Bill");
        Bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillActionPerformed(evt);
            }
        });

        Postpaid.setMnemonic('P');
        Postpaid.setText("Postpaid");
        Postpaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostpaidActionPerformed(evt);
            }
        });

        Login.setMnemonic('L');
        Login.setText("Logout");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        jLabel1.setText("Menu");

        Purchase.setMnemonic('C');
        Purchase.setText("Purchase");
        Purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseActionPerformed(evt);
            }
        });

        Queue.setMnemonic('Q');
        Queue.setText("Queue");
        Queue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueueActionPerformed(evt);
            }
        });

        Pending.setMnemonic('E');
        Pending.setText("Pending");
        Pending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendingActionPerformed(evt);
            }
        });

        BillStatistics.setMnemonic('S');
        BillStatistics.setText("Bill Statistics");
        BillStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillStatisticsActionPerformed(evt);
            }
        });

        MenuCard.setMnemonic('C');
        MenuCard.setText("Menu Card");
        MenuCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(UserRegistration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuyerRegistration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FoodRegistration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Purchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pending, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BillStatistics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Postpaid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Queue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MenuCard)
                .addGap(46, 46, 46)
                .addComponent(Login)
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserRegistration)
                    .addComponent(Bill)
                    .addComponent(Postpaid))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FoodRegistration)
                    .addComponent(Purchase)
                    .addComponent(BillStatistics))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuyerRegistration)
                    .addComponent(Pending)
                    .addComponent(Queue))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login)
                    .addComponent(MenuCard))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FoodRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoodRegistrationActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FoodRegistration().setVisible(true);
    }//GEN-LAST:event_FoodRegistrationActionPerformed

    private void BuyerRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyerRegistrationActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new BuyerRegistration().setVisible(true);
    }//GEN-LAST:event_BuyerRegistrationActionPerformed

    private void UserRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserRegistrationActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new UserRegistration().setVisible(true);
    }//GEN-LAST:event_UserRegistrationActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginPage().setVisible(true);
        try {
            java.nio.file.Files.write(java.nio.file.Paths.get(System.getProperty("user.dir") + "\\lib\\log.txt"), LoginPage.encrypt(new java.util.Date(System.currentTimeMillis()).toString()
                    + " Logged Out\n\n").getBytes(), java.nio.file.StandardOpenOption.APPEND);
        } catch (java.io.IOException ex) {
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void BillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Bills1().setVisible(true);
    }//GEN-LAST:event_BillActionPerformed

    private void PostpaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostpaidActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Postpaid().setVisible(true);
    }//GEN-LAST:event_PostpaidActionPerformed

    private void PurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Purchase().setVisible(true);
    }//GEN-LAST:event_PurchaseActionPerformed

    private void QueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueueActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Queues().setVisible(true);
    }//GEN-LAST:event_QueueActionPerformed

    private void PendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendingActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Pending().setVisible(true);
    }//GEN-LAST:event_PendingActionPerformed

    private void BillStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillStatisticsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new BillStatatics().setVisible(true);
    }//GEN-LAST:event_BillStatisticsActionPerformed

    private void MenuCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCardActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Menu().setVisible(true);
    }//GEN-LAST:event_MenuCardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bill;
    private javax.swing.JButton BillStatistics;
    private javax.swing.JButton BuyerRegistration;
    private javax.swing.JButton FoodRegistration;
    private javax.swing.JButton Login;
    private javax.swing.JButton MenuCard;
    private javax.swing.JButton Pending;
    private javax.swing.JButton Postpaid;
    private javax.swing.JButton Purchase;
    private javax.swing.JButton Queue;
    private javax.swing.JButton UserRegistration;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
